### ISSUE TITLE
3.18.1 regression when webmock is used with datadog

### ISSUE THREAD

**Issue by HoneyryderChuck** [bblimke/webmock#1025]
After upgrading to 3.18.1, the [CI suite of httpx](https://gitlab.com/os85/httpx/-/jobs/4196226641) started reporting errors for the datadog tests (which are run with webmock tests). For the record, the stub request recommendation happens when webmock is disabled (I could reproduce it with a `Webmock.disable!` call right before the call which causes the failure). The call is in itself unrelated with `httpx` (it's a call to `net-http` happening inside the datadog sdk).

I'm assuming something weird happened [here](https://github.com/bblimke/webmock/commit/4baddbf804204a2ae86f41f0c98110c2b57ee65d), and given both webmock and datadog monkeypatch `net-http`, they kind of cancelled each other out? ~~Downgrading to 0.18.0 fixed it for me.~~ It actually didn't.

**Comment by bblimke** [comment]
@HoneyryderChuck as I understand the issue is not related to version 3.18.1 but some earlier version of WebMock? What is the last version that works? Is this due to a change in WebMock or due to a changed in ddtrace?

It's difficult to support for setups where two separate libs monkeypatch the http library unfortunately.

Have you tried changing the order of when ddtrace monkeypatch is applied and `WebMock.enable!` is called?

**Comment by HoneyryderChuck** [comment]
hey @bblimke I believe the issue was related with the datadog patch, and this has been fixed (see related ddtrace ticket and comments). Will close it.

> It's difficult to support for setups where two separate libs monkeypatch the http library unfortunately.

I wholeheartedly agree, but this is how sadly most observability / mock / logging / etc library adds behaviour to practically all of ruby http clients, to which webmock is also no exception.
