### ISSUE TITLE
CI consistently failing on Ruby >= 3.1, is it ok to update?

### ISSUE THREAD

**Issue by tagliala** [bblimke/webmock#1036]
Hi,

given the broken status badge and the results at 

https://github.com/bblimke/webmock/actions/runs/6021150216/

It is not clear if the current version is supposed to work with Ruby >= 3.1

I did upgrade to 3.19 and webmock is still working, but I would ask for a confirmation

**Comment by bblimke** [comment]
It Async HTTP specs started failing for no good reason or ruby 3.1 and 3.2. No idea why as they passed few days before. Webmock oś compatible with both 3.1 and 3.2

**Comment by mattbrictson** [comment]
I figured out that the Async HTTP specs are failing due to the `async` gem. Version 2.6.4 was released on Aug 25, 2023 and subsequently causes the the Async HTTP specs to fail.

By bisecting commits, I narrowed the cause down to this specific PR that seems to have had the (intended? unintended?) effect of changing exception behavior: https://github.com/socketry/async/pull/270

The result is that Async HTTP calls that used to raise exceptions with `async` <= 2.6.3 now do not raise exceptions on 2.6.4.

I've never used Async HTTP so I don't know if this is a problem that should be reported upstream, or if webmock's Async HTTP support needs to be changed to support the new behavior.

In any case I would really like to see green CI builds here. Would the maintainers be open to pinning `async < 2.6.4` in the gemspec for the time being to get a green build?
