### ISSUE TITLE
Specs not running with elasticsearch

### ISSUE THREAD

**Issue by RKushnir** [bblimke/webmock#163]
I'm using webmock 1.7.10 and elasticsearch+tire(https://github.com/karmi/tire). When running the specs it tries to access localhost:9200 on start and webmock halts the process because this request is not stubbed. I tried `WebMock.disable!` in `spec_helper.rb` right after `require 'webmock/rspec'` but this didn't help. Then tried stubbing that URL but it didn't help either.

```
WebMock.disable_net_connect!(:allow_localhost => true)
```

and

```
WebMock.allow_net_connect!
```

also didn't work.

Is there any solution or workaround? This is not specific to some particular specs, this prevents me from being able to run specs at all, so it's a major issue for me, please advice.

**Comment by welligton1993** [comment]
Thanks!

**Comment by robertomiranda** [comment]
@aptx4869 :+1:

**Comment by frenkel** [comment]
IMHO it is better to add `require: false` to the `gem 'webmock'` line in Bundler, then load webmock with a require in your test_helper and right after that disable it for localhost.

**Comment by bblimke** [comment]
@frenkel thanks for suggestion!

**Comment by chase439** [comment]
Thank you for your work on the gem.

I've been getting sporadic corruption and failures in my rspec test suite. Similar to the discussion in this thread, I have `gem 'webmock', require: false` in my Gemfile. Basically, my question is How do I enable real requests by default for the case I have below?

I have a test __file1__ (for testing fake requests) that `require 'webmock/rspec'` and cleans up after itself by stubbing request and  `WebMock.allow_net_connect!` after all its tests complete.  Also, I have a test __file2__ (for testing real requests) that has no `require 'webmock/rspec'`. 

I realized that if __file2__ runs first, then its real requests would fail. I believe this is because rspec loads all the test files and its require statements, which in my case a `require 'webmock/rspec'` in any files would disable all real requests across the suite. For many test files that use real requests, I don't want to put `WebMock.allow_net_connect!` in each of those files when they don't really need to know about webmock. 

The suggestion to add the following to the top of spec_helper.rb:

    require 'webmock'
    WebMock.allow_net_connect!

kind of work, but breaks my spork (yes, it's kinda old technology) with cryptic errors. My question: Is there another way?

**Comment by chase439** [comment]
I overlooked it, but the suggestion by @aptx4869 to add `config/initializers/webmock.rb` solved my spork issue and allowed real requests by default. Hopefully my use case above can add a point to enable real connections by default ;)
