### ISSUE TITLE
No support for Manticore

### ISSUE THREAD

**Issue by ebenoist** [bblimke/webmock#454]
Currently Webmock lacks support for the [manticore](https://github.com/cheald/manticore) HTTP client library as it is implemented with the Apache Commons HTTP library (and is thus JRuby only). A recent PR was merged into the manticore library to support [regexps](https://github.com/cheald/manticore/pull/16), which may allow for webmock support. Though other changes may need to be made to allow manticore's stubbing support to have parity with webmock.

I am interested in adding this support if the maintainer would be interested, but wanted your advice on approaches. I imagine it would involve adding a new http library adapter and following something like the typhoeus adapter pattern while swapping out the typhoeus mocks for manticore's stubbing support.

Any advice would be appreciated.

**Comment by bblimke** [comment]
In order to add new manticore client support you need to add `manticore_spec.rb` and `manticore_spec_helper.rb` inside `spec/acceptance/manticore/`based on examples from other libs.
As a base the spec needs to `include_context "with WebMock"`. 

Then you can proceed with implementing the adapter. When all specs are passing, the support is complete.

Since each new library adds maintenance overhead to WebMock, it's best to keep WebMock support only for the most popular clients. Do you think manticore is popular enough?

**Comment by jkingdon** [comment]
As for "only for the most popular clients", manticore seems the leading candidate at [Square](http://square.github.io/) to wean us off `Net::HTTP` for jruby apps. I believe the reasons have to do primarily with the "robust" in "Manticore is a fast, robust . . ." at https://github.com/cheald/manticore (connection pooling and so on) but I could dig up more details if needed.

**Comment by jkingdon** [comment]
Hmm, that particular choice seems to be out of date (in favor of https://github.com/httprb/http.rb ). That's just one data point, I don't really know about manticore's popularity in general.

**Comment by presidentJFK** [comment]
closing now that #523 is merged in
