### ISSUE TITLE
WebMock doesn't raise exception when specifying headers as symbols using Net::HTTP

### ISSUE THREAD

**Issue by steveklebanoff** [bblimke/webmock#486]
When making a Net::HTTP request specifying headers as symbols, an exception is raised.  If you stub the request using WebMock, an exception is not raised, and it acts as though the request is successful.

This can cause a major headache:  trying to make this request raises an exception in the real world, but passes when the request is stubbed with WebMock.

@cjlarose and I have created an isolated project to highlight this behavior.  Please see  https://github.com/cjlarose/webmock-net-http-headers-bug

**Comment by bblimke** [comment]
@steveklebanoff looks like it's a problem in WebMock indeed.

It may not be trivial to fix it though. Net::HTTP doesn't handle invalid headers but an unexpected error is raised when expecting string. WebMock intercepts the request before it reaches problematic code in header.rb.

**Comment by presidentJFK** [comment]
So I made a Pull Request #515 mirroring Net::HTTP's functionality, by just checking the headers for symbols before normalizing them and raising a NoMethodError with identical error message.

I need to see how the other http adapters work with headers, but this change at least fixes issue for Net::HTTP.

The only question is whether we should raise an error saying Net::HTTP doesn't except headers as symbols, which would be more useful than this error.

opinions? @bblimke @steveklebanoff 

otherwise I am going to merge this in, as it does prevent a false positive in a test.

**Comment by cjlarose** [comment]
Nice work @presidentJFK! Left a [comment][1] on the PR.

[1]: https://github.com/bblimke/webmock/pull/515/files#r38891939

**Comment by steveklebanoff** [comment]
Thank you for doing this @presidentJFK ! Looks awesome.

**Comment by presidentJFK** [comment]
closing now that #515 is merged in.

**Comment by bblimke** [comment]
well done @presidentJFK

**Comment by akestner** [comment]
Run into some odd behavior related to this issue.  For some reason (with Ruby 2.3.0), my non-mocked requests with symbol headers work fine, but fail in my tests due to the associated PR (#515).  

Any ideas?
