### ISSUE TITLE
Should not depend on safe_yaml

### ISSUE THREAD

**Issue by spjsschl** [bblimke/webmock#496]
safe_yaml changes how the YAML parser that comes with ruby behaves. By pulling in safe_yaml (via crack) webmock causes inconsistencies between parsing a YAML file in production and test environments. A possible workaround is to require safe_yaml in production. Yet I feel webmock should not dictate how the app parses YAML.

**Comment by bblimke** [comment]
@spjsschl thanks for reporting that.

As I can see safe_yaml is only used by Crack json parser https://github.com/jnunemaker/crack/blob/master/lib/crack/json.rb
WebMock uses own JSON parser nowadays (extracted from previous version of Crack) 

Perhaps it's enough if WebMock requires 'crack/xml', instead of 'crack' and the problem will be solved.

**Comment by spjsschl** [comment]
That sounds, like it would work.

**Comment by bblimke** [comment]
@spjsschl great. I'll do it when I find some time, unless you fancy a pull request :)

**Comment by spjsschl** [comment]
I added a PR: https://github.com/bblimke/webmock/pull/497

FWIW, the same 39 tests are failing on my local machine before and after my change
