### ISSUE TITLE
webmock enabled on require

### ISSUE THREAD

**Issue by lanej** [bblimke/webmock#583]
Requiring Webmock immediately enables it.  I believe that this is bad behavior and should change.  Given that it's probably expected behavior at this point, it should at least be documented. Probably something in 
https://github.com/bblimke/webmock#disabling-and-enabling-webmock-or-only-some-http-client-adapters

Offending commit: https://github.com/bblimke/webmock/commit/b3d60450e49e724a38a40d4f98fafdfed611ebd3#diff-9c446f800dcca622179ac9fd536cb7e1R100

**Comment by bblimke** [comment]
Thank you for raising it and sharing your opinion.

This is expected and desired behaviour and was in WebMock by design since the beginning.

Many developers are surprised how many unexpected external requests their test make,
when they require WebMock in test env.

You are right that it should be documented though.

I haven't decided whether to keep this behaviour in version 2 or not. I believe I have heard more times that people were happy with WebMock blocking all connections by default than otherwise.

**Comment by lanej** [comment]
Thanks for replying.  As I don't believe side effects are meant to be part of loading a library, my vote is obvious.  Versioning it out on the next major bump would be an excellent way to solve the issue.

I would be happy to submit a PR for the documentation.

**Comment by bblimke** [comment]
I'd be very happy to accept the PR with documentation updated :)
