### ISSUE TITLE
Memory leak after many requests have been made

### ISSUE THREAD

**Issue by perlun** [bblimke/webmock#714]
Hi,

While I was [debugging a hard-to-reproduce memory leak](http://perlun.eu.org/en/2017/08/24/debugging-hard-to-reproduce-ruby-memory-leaks) (which turned out to be a known-and-fixed MRI bug) I noted this:

![image](https://user-images.githubusercontent.com/630613/30211570-3bf09d0e-94aa-11e7-9723-716b520f5cb4.png)

This is the number of `old_objects` being plotted over time, when recording requests with VCR (using `webmock` as the backend).

I don't have the exact script at hand, at the moment, but it was really not so fancy: recording perhaps 10-20 different URLs with VCR, running a high number of requests would trigger this. It's _likely_ that just making 1 000 000 requests with Webmock will show a similar behavior.

Do you consider this "by design" or could it be a bug in wemock or VCR?

Thanks for a great gem!

**Comment by bblimke** [comment]
@perlun it is "by design"

Webmock keeps `RequestRegistry` and stores signatures of all executed requests,
therefore the registry grows over time.

The `RequestRegistry` is required for matching configured expectations of executed requests.

I guess it's a rare scenario to execute 1 000 000 requests via WebMock,
and that's why nobody has complained about that before.

You can always clear the `RequestRegistry` with `WebMock::RequestRegistry.instance.reset!`

**Comment by perlun** [comment]
> Webmock keeps RequestRegistry and stores signatures of all executed requests,
> therefore the registry grows over time.

OK, that's fine and expected. But is this the case even when making a request with the exact same URL over and over again also?

(It's not a major issue for me, I'm just curious now. The root cause of my original problem has been found and I am happy. 😄)

**Comment by bblimke** [comment]
@perlun The same url should just increase the counter, therefore I would not expect the memory issues.

In that case it's worth investigating whether it's on VCR or Webmock side.

**Comment by perlun** [comment]
I will not be pursuing this further, so closing. Thanks for your help @bblimke!
