### ISSUE TITLE
Ability to reset a chain stub

### ISSUE THREAD

**Issue by itmart** [bblimke/webmock#817]
Hello,

My application is using a chain stub with WebMock like so:

```ruby
stub_request(:any, domain).to_return(body: first_response.to_json).then
                          .to_return(body: second_response.to_json)
```

The test I'm running calls the method to make the external call twice. I found out the only way for this to work is to call that same `stub_request` again after the first time the app makes the external call, or else the second time the app makes the external call, `second_response` is returned twice.

Is there a way to reset the chain? It feels a little un-dry to have to call `stub_request` twice, or having to chain 4 responses with 2 being duplicates.

Thank you!

**Comment by bblimke** [comment]
Hi @itmart 

> or else the second time the app makes the external call, second_response is returned twice.

Could you please provide a code sample or a failing spec to demonstrate that the `second_response ` is returned twice?

**Comment by itmart** [comment]
Sorry I've been a little busy these past few weeks. As soon as I have some free time, I'll try to write up one!

**Comment by itmart** [comment]
@bblimke Sorry for super long delay, but I've finally got the time to write up a simple spec:

```ruby
class TestWebmock
  require 'httparty'

  def self.hit_endpoint_one
    array = []
    2.times do
      endpoint = "http://test.com"
      response = HTTParty.get(endpoint)
      array << response.body
    end
    array
  end

  def self.hit_endpoint_two
    array = []
    2.times do
      endpoint = "http://test.com"
      response = HTTParty.get(endpoint)
      array << response.body
    end
    array
  end
end

RSpec.describe TestWebmock do
  require 'webmock/rspec'
  WebMock.disable_net_connect!(allow_localhost: true)

  it "recreates issue with WebMock" do
    # Arrange
    endpoint = "test.com"
    stub_request(:any, endpoint).to_return(body: "1").then
                                .to_return(body: "2")

    # Act/Assert
    expect(TestWebmock.hit_endpoint_one).to eq(["1", "2"])
    expect(TestWebmock.hit_endpoint_two).to eq(["1", "2"])
  end
end
```

Let me know if you need anything else from me!

**Comment by bblimke** [comment]
@itmart ok thank you. I understand the issue now. 

This is all by design.

Webmock first returns all responses and then it starts returning the last response infinitely.

It doesn't return to the first response again, after returning the last one.

This is not a loop of responses but a simple list.

WebMock doesn't know your intentions. You have split your code into two methods, but WebMock doesn't know that you expect to return the same two responses twice, starting from the first one again.

If you want "1", "2" and then again "1" and "2" to be retuned, you have to do:

`stub_request(:any, endpoint).to_return(body: "1").then.to_return(body: "2").then.to_return(body: "1").then.to_return(body: "2")`

or simply

stub_request(:any, endpoint).to_return({body: "1"}, {body: "2"}, {body: "1"}, {body: "2"})

**Comment by itmart** [comment]
Ah I see, I was hoping that I was doing something wrong and there would be a way to not have to repeat the return values, but if there isn't one it's not the end of the world. Thank you for your response!
