### ISSUE TITLE
Can I Add Net::FTP Support?

### ISSUE THREAD

**Issue by thejamespinto** [bblimke/webmock#818]
First off, I was shocked to see nobody else suggested this. The only close ref I found was #801 

I think the best way I could go about this would be writing a side extension to webmock in a separate codebase.

Have other people tried this before?

Is this something you'd be ultimately interested in merging such extension to the main codebase?

Thanks!
The code examples here will def help me get this done more quickly.

**Comment by bblimke** [comment]
Hi James. 

The main purpose of WebMock was to simplify and unify testing/mocking/verification of http requests which is http client independent.

If the FTP was only to support Net::FTP, then it's not as much value, since mocking using FTP requests using Webmock would require similar amount of work as simply mocking Net::FTP.

WebMock is all about HTTP therefore not sure if FTP would fit there. Probably another gem, like FTPMock would make more sense.

**Comment by thejamespinto** [comment]
Hi Bartosz,

I have a (absolutely not) working prototype for my own needs that I wrote in like 30 minutes.

I have been thinking of doing this for ages.

I'll send you a link asking for input when I'm good to outsource this.

Thank you so much for writing this gem. Your codebase was amazing inspiration.

Cheers!

**Comment by bblimke** [comment]
Thank you James! I'll be very happy to have a look at your solution when it's ready.
