### ISSUE TITLE
Incorrect Ruby compatibility in gemspec

### ISSUE THREAD

**Issue by arielj** [bblimke/webmock#995]
Since version 3.15.0, webmock is incompatible with Ruby 2.2 or older because it started using the `&.` syntax here https://github.com/bblimke/webmock/blob/v3.15.0/lib/webmock/request_signature.rb#L38.

It's still reporting Ruby >= 2.0 in the gemspec so `bundle install` install this version incorrectly when it should pick 3.14.0.

It does work fine for Ruby >= 2.0 with version 3.14.0.

**Comment by bblimke** [comment]
@arielj sorry for that. 

I have released 3.15.1 and 3.16.1 with required ruby 2.3,
and I have yanked 3.15.0 and 3.16.0

**Comment by arielj** [comment]
thanks!

**Comment by benlangfeld** [comment]
@bblimke Hey! Thanks for fixing this. Unfortunately yanking gems in this case quite possibly caused more breakage in application delivery than those few people still using Ruby < 2.3. Yanking gems should only really be done if there are urgent security concerns in a release, and not just because it is in some way broken. I appreciate all of your efforts in open source maintenance, and I know from personal experience how hard it is, but I feel an obligation to spread the word about the dangers of withdrawing packages.

**Comment by arielj** [comment]
Can a released gem be updated with the correct ruby requirement? I feel like that should be safer than yanking (I don't know if a version can be `un-yanked` either)

**Comment by benlangfeld** [comment]
> Can a released gem be updated with the correct ruby requirement? I feel like that should be safer than yanking (I don't know if a version can be `un-yanked` either)

No. Modifying a release is just as bad or worse than yanking it. I don't believe a yanked gem can be re-published.

The most appropriate solution here would have been to publish a new fixed version as was done, but without yanking the prior broken versions; by doing so, those who already encountered breakage can fix it by upgrading and you don't break anyone for whom the previous releases were working.

**Comment by bblimke** [comment]
I'm sorry for the mess created 🤦 Yanking was a bad idea.

@benlangfeld thank you for the useful feedback.

> The most appropriate solution here would have been to publish a new fixed version as was done, but without yanking the prior broken versions; by doing so, those who already encountered breakage can fix it by upgrading and you don't break anyone for whom the previous releases were working.

I agree, but the fixed versions should have been fixed, by making 3.15 and 3.16 ruby < 2.3 compatible,
and not by increasing the ruby version requirement in the gemspec, as I have done.

I believe that if I haven't yanked the 3.15.0 and 3.16.0, then Ruby < 2.3 would still try installing 3.15.0 and 3.16.0,
since 3.15.1 and 3.16.1 require Ruby >= 2.3.

I'm till considering creating 3.15.2 and 3.16.2, Ruby >= 2.0 compatible if it is useful to anyone.

**Comment by JBallin** [comment]
The fix is easy enough, but it would be useful to surface this communication more clearly.

Some ideas:
* https://github.com/bblimke/webmock/tags (+ CHANGELOG too maybe) - add note to yanked versions
* Create and [pin](https://docs.github.com/en/issues/tracking-your-work-with-issues/pinning-an-issue-to-your-repository) a new issue with a summary

**Comment by bblimke** [comment]
@JBallin how can I add notes to the tags page?

**Comment by arielj** [comment]
> I'm till considering creating 3.15.2 and 3.16.2, Ruby >= 2.0 compatible if it is useful to anyone.

My use case was running tests for the next_rails gem that we use at work to upgrade old apps so we need the old ruby support for the gem's tests, but it's enough for us to pin the version to 3.14.0 so no need at least for us to have 3.15+ with support for ruby 2.

**Comment by JBallin** [comment]
I don't have direct experience with tags, but you should be able to [annotate them](https://git-scm.com/book/en/v2/Git-Basics-Tagging) and it appears you could [alter existing tags](https://stackoverflow.com/q/7813194/4722345), but this may not be worth the effort. Pinning an issue is likely easier.
